export {default as HomeScreen} from './HomeScreen/HomeScreen'
export {default as DetailsScreen} from './DetailsScreen/DetailsScreen'
export {default as SettingScreen} from './SettingScreen/SettingScreen'
export {default as ComicDetails} from './ComicDetails/ComicDetails'
export {default as ComicReader} from './ComicReader/ComicReader'
export {default as Ranking} from './Ranking/Ranking'
export {default as Test} from './Test/Test'