export {default as HomeScreen} from './HomeScreen/HomeScreen'
export {default as DetailsScreen} from './DetailsScreen/DetailsScreen'
export {default as SettingScreen} from './SettingScreen/SettingScreen'
export {default as ComicDetails} from './ComicDetails/ComicDetails'
export {default as ComicReader} from './ComicReader/ComicReader'
export {default as ComicRanking} from './ComicRanking/ComicRanking'
export {default as ComicNewUpdate} from './ComicNewUpdate/ComicNewUpdate'
export {default as Test} from './Test/Test'